#!/usr/bin/env python3

"""
Test Collections System with Email Logging
This tests the collections system and shows what emails would be sent
"""

import sqlite3
import json
from datetime import datetime

def test_collections_with_email_logging():
    """Test the collections system and show email content"""
    
    print("🧪 Testing Collections System with Email Logging")
    print("=" * 60)
    
    try:
        # Connect to local SQLite database
        conn = sqlite3.connect('gym_bot.db')
        cursor = conn.cursor()
        
        # Get past due members
        cursor.execute("""
            SELECT 
                full_name as name,
                email,
                phone,
                amount_past_due as past_due_amount,
                'member' as type
            FROM members 
            WHERE amount_past_due > 0
            ORDER BY amount_past_due DESC
            LIMIT 5
        """)
        
        past_due_members = cursor.fetchall()
        
        # Get past due training clients
        cursor.execute("""
            SELECT 
                member_name as name,
                email,
                phone,
                past_due_amount,
                'training_client' as type,
                package_details
            FROM training_clients 
            WHERE past_due_amount > 0
            ORDER BY past_due_amount DESC
            LIMIT 5
        """)
        
        past_due_training = cursor.fetchall()
        
        # Process training clients to extract agreement info
        processed_training = []
        for client in past_due_training:
            client_dict = {
                'name': client[0], 'email': client[1], 'phone': client[2],
                'past_due_amount': client[3], 'type': client[4], 'package_details': client[5]
            }
            
            # Extract agreement info from package_details
            agreement_id = None
            agreement_type = None
            if client_dict.get('package_details'):
                try:
                    details = json.loads(client_dict['package_details'])
                    if details and len(details) > 0:
                        agreement_id = details[0].get('agreement_id')
                        agreement_type = details[0].get('package_name', 'Training Package')
                except:
                    pass
            
            client_dict['agreement_id'] = agreement_id
            client_dict['agreement_type'] = agreement_type
            processed_training.append(client_dict)
        
        # Combine all past due data
        all_past_due = []
        
        # Add members
        for member in past_due_members:
            all_past_due.append({
                'name': member[0], 'email': member[1], 'phone': member[2],
                'past_due_amount': member[3], 'type': member[4],
                'agreement_id': None, 'agreement_type': None
            })
        
        # Add training clients
        all_past_due.extend(processed_training)
        
        print(f"✅ Found {len(all_past_due)} past due accounts")
        
        # Test email generation with first 3 accounts
        test_accounts = all_past_due[:3]
        total_amount = sum(account['past_due_amount'] for account in test_accounts)
        
        print(f"\n📧 Sample Collections Email (Top 3 accounts, Total: ${total_amount:.2f})")
        print("=" * 80)
        
        email_content = f"""
COLLECTIONS REFERRAL - {datetime.now().strftime('%Y-%m-%d')}

The following accounts have been selected for collections referral:

"""
        
        for i, account in enumerate(test_accounts, 1):
            name = account.get('name', 'Unknown')
            amount = account.get('past_due_amount', 0)
            email = account.get('email', 'No email')
            phone = account.get('phone', 'No phone')
            account_type = account.get('type', 'Unknown')
            agreement_id = account.get('agreement_id', 'N/A')
            agreement_type = account.get('agreement_type', 'N/A')
            
            email_content += f"""
{i}. {name}
   Amount Past Due: ${amount:.2f}
   Type: {account_type.title()}
   Agreement ID: {agreement_id}
   Agreement Type: {agreement_type}
   Email: {email}
   Phone: {phone}
   ---
"""
        
        email_content += f"""

TOTAL AMOUNT: ${total_amount:.2f}
TOTAL ACCOUNTS: {len(test_accounts)}

Please process these accounts for collections referral.

Generated by Gym Bot Collections Manager
"""
        
        print(email_content)
        
        print("\n" + "=" * 80)
        print("📋 Email Details:")
        print(f"   From: fdl.gym.bot@gmail.com")
        print(f"   To: FondDuLacWI@anytimefitness.com")
        print(f"   Subject: Collections Referral - {datetime.now().strftime('%Y-%m-%d')}")
        print(f"   Accounts: {len(test_accounts)}")
        print(f"   Total Amount: ${total_amount:.2f}")
        
        print("\n✅ Collections system is working correctly!")
        print("📧 Email content generated successfully")
        print("⚠️  To enable actual email sending, set up Gmail App Password")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Error testing collections system: {e}")
        import traceback
        print(f"❌ Traceback: {traceback.format_exc()}")
        return False

if __name__ == "__main__":
    test_collections_with_email_logging()
