#!/usr/bin/env python3

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def test_email_sending():
    """Test the email sending functionality using existing bot credentials"""
    
    print("🧪 Testing Email Sending Functionality")
    print("=" * 50)
    
    try:
        # Get email credentials from SecureSecretsManager
        from src.services.authentication.secure_secrets_manager import SecureSecretsManager
        secrets_manager = SecureSecretsManager()
        
        # Use existing bot credentials
        sender_email = "fdl.gym.bot@gmail.com"
        sender_password = secrets_manager.get_secret("gmail-password")
        
        if not sender_password:
            print("❌ Gmail password not found in secrets manager!")
            print("Please ensure 'gmail-password' is stored in the secrets manager")
            return False
        
        print("✅ Using regular Gmail password (2-step verification disabled)")
        
        print(f"✅ Sender email: {sender_email}")
        print(f"✅ Password: {'*' * len(sender_password)}")
        
    except Exception as e:
        print(f"❌ Error accessing secrets manager: {e}")
        return False
    
    # Test email content
    test_content = f"""
COLLECTIONS REFERRAL - {datetime.now().strftime('%Y-%m-%d')}

The following accounts have been selected for collections referral:

1. Test Member
   Amount Past Due: $150.00
   Type: Member
   Agreement ID: 12345678
   Agreement Type: Membership
   Email: test@example.com
   Phone: +1234567890
   ---

TOTAL AMOUNT: $150.00
TOTAL ACCOUNTS: 1

Please process these accounts for collections referral.

Generated by Gym Bot Collections Manager
"""
    
    # Email configuration
    smtp_server = "smtp.gmail.com"
    smtp_port = 587
    recipient_email = "FondDuLacWI@anytimefitness.com"
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = f"Collections Referral Test - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Add body to email
        msg.attach(MIMEText(test_content, 'plain'))
        
        print(f"\n📧 Attempting to send test email to {recipient_email}...")
        
        # Create SMTP session
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()  # Enable TLS encryption
        
        # Login with the stored password (2-step verification is disabled)
        server.login(sender_email, sender_password)
        
        # Send email
        text = msg.as_string()
        server.sendmail(sender_email, recipient_email, text)
        server.quit()
        
        print("✅ Test email sent successfully!")
        print(f"📧 Email sent to: {recipient_email}")
        print("📧 Subject: Collections Referral Test")
        print("📧 Content: Test collections referral with sample data")
        
        return True
        
    except smtplib.SMTPAuthenticationError as e:
        print(f"❌ Email authentication failed: {e}")
        print("\n🔧 Troubleshooting steps:")
        print("1. Make sure 2-Step Verification is OFF")
        print("2. Enable 'Less Secure App Access' in Gmail settings")
        print("3. Or try using an App Password instead")
        print("4. Check that the password in secrets manager is correct")
        return False
        
    except smtplib.SMTPException as e:
        print(f"❌ SMTP error: {e}")
        return False
        
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        return False

if __name__ == "__main__":
    test_email_sending()