#!/usr/bin/env python3

import sqlite3
import json
from datetime import datetime

def get_past_due_collections_sqlite():
    """Get all past due members and training clients for collections management using SQLite"""
    try:
        conn = sqlite3.connect('gym_bot.db')
        cursor = conn.cursor()
        
        # Get past due members
        cursor.execute("""
            SELECT 
                full_name as name,
                email,
                phone,
                mobile_phone,
                amount_past_due as past_due_amount,
                status,
                join_date,
                'member' as type,
                NULL as agreement_id,
                NULL as agreement_type
            FROM members 
            WHERE amount_past_due > 0
            ORDER BY amount_past_due DESC
        """)
        
        past_due_members = cursor.fetchall()
        
        # Get past due training clients with agreement data
        cursor.execute("""
            SELECT 
                member_name as name,
                email,
                phone,
                past_due_amount,
                payment_status as status,
                last_updated,
                'training_client' as type,
                package_details,
                active_packages
            FROM training_clients 
            WHERE past_due_amount > 0
            ORDER BY past_due_amount DESC
        """)
        
        past_due_training = cursor.fetchall()
        
        # Process training clients to extract agreement info
        processed_training = []
        for client in past_due_training:
            client_dict = {
                'name': client[0], 'email': client[1], 'phone': client[2],
                'past_due_amount': client[3], 'status': client[4], 'last_updated': client[5],
                'type': client[6], 'package_details': client[7], 'active_packages': client[8]
            }
            
            # Extract agreement info from package_details
            agreement_id = None
            agreement_type = None
            if client_dict.get('package_details'):
                try:
                    details = json.loads(client_dict['package_details'])
                    if details and len(details) > 0:
                        agreement_id = details[0].get('agreement_id')
                        agreement_type = details[0].get('package_name', 'Training Package')
                except:
                    pass
            
            client_dict['agreement_id'] = agreement_id
            client_dict['agreement_type'] = agreement_type
            processed_training.append(client_dict)
        
        # Combine all past due data
        all_past_due = []
        
        # Add members
        for member in past_due_members:
            member_dict = {
                'name': member[0], 'email': member[1], 'phone': member[2],
                'mobile_phone': member[3], 'past_due_amount': member[4], 'status': member[5],
                'join_date': member[6], 'type': member[7], 'agreement_id': member[8],
                'agreement_type': member[9]
            }
            all_past_due.append(member_dict)
        
        # Add training clients
        all_past_due.extend(processed_training)
        
        conn.close()
        
        return {
            'success': True,
            'past_due_data': all_past_due,
            'total_count': len(all_past_due)
        }
        
    except Exception as e:
        print(f"❌ Error getting past due collections data: {e}")
        return {'success': False, 'error': str(e)}

def generate_collections_email(selected_accounts):
    """Generate email content for collections list"""
    email_content = f"""
COLLECTIONS REFERRAL - {datetime.now().strftime('%Y-%m-%d')}

The following accounts have been selected for collections referral:

"""
    
    total_amount = 0
    for i, account in enumerate(selected_accounts, 1):
        name = account.get('name', 'Unknown')
        amount = account.get('past_due_amount', 0)
        email = account.get('email', 'No email')
        phone = account.get('phone', 'No phone')
        account_type = account.get('type', 'Unknown')
        agreement_id = account.get('agreement_id', 'N/A')
        agreement_type = account.get('agreement_type', 'N/A')
        
        total_amount += amount
        
        email_content += f"""
{i}. {name}
   Amount Past Due: ${amount:.2f}
   Type: {account_type.title()}
   Agreement ID: {agreement_id}
   Agreement Type: {agreement_type}
   Email: {email}
   Phone: {phone}
   ---
"""
    
    email_content += f"""

TOTAL AMOUNT: ${total_amount:.2f}
TOTAL ACCOUNTS: {len(selected_accounts)}

Please process these accounts for collections referral.

Generated by Gym Bot Collections Manager
"""
    
    return email_content

if __name__ == "__main__":
    # Test the collections data
    result = get_past_due_collections_sqlite()
    if result['success']:
        print(f"✅ Found {result['total_count']} past due accounts")
        
        # Test email generation with first 3 accounts
        test_accounts = result['past_due_data'][:3]
        email_content = generate_collections_email(test_accounts)
        print("\n📧 Sample email content:")
        print(email_content)
    else:
        print(f"❌ Error: {result['error']}")
